Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/srv/conda/envs/notebook/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Standard python numerical analysis imports:
import numpy as np
from scipy import signal
from scipy.interpolate import interp1d
from scipy.signal import butter, filtfilt, iirdesign, zpk2tf, freqz
import h5py
import json

# the IPython magic below must be commented out in the .py file, since it doesn't work there.
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
import matplotlib.pyplot as plt
import matplotlib.mlab as mlab

# LIGO-specific readligo.py 
from ligotools import readligo as rl

#LIGO-specific utils.py
from ligotools import utils as ul

# you might get a matplotlib warning here; you can ignore it.
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 16>[0;34m()[0m
[1;32m     13[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mmlab[39;00m [38;5;28;01mas[39;00m [38;5;21;01mmlab[39;00m
[1;32m     15[0m [38;5;66;03m# LIGO-specific readligo.py [39;00m
[0;32m---> 16[0m [38;5;28;01mfrom[39;00m [38;5;21;01mligotools[39;00m [38;5;28;01mimport[39;00m readligo [38;5;28;01mas[39;00m rl
[1;32m     18[0m [38;5;66;03m#LIGO-specific utils.py[39;00m
[1;32m     19[0m [38;5;28;01mfrom[39;00m [38;5;21;01mligotools[39;00m [38;5;28;01mimport[39;00m utils [38;5;28;01mas[39;00m ul

[0;31mModuleNotFoundError[0m: No module named 'ligotools'
ModuleNotFoundError: No module named 'ligotools'

